//HW1 Problem a
//JohnAnthony Dobson
//CS 3335
//8/25/18

/* Write a C-program to guess a random integer, between 0 and 100, 
that has been generated by the program. The program should restrict 
user for fixed number of trials (maximum 10). Each incorrect guess 
should be identified as “Too high” or “Too low”. If guessed correctly 
within the trial limit, appropriate success message should be displayed 
before terminating the program. If number of attempts is exhausted, 
the user should be notified and the generated number should be displayed 
before terminating the program. Use global constant to set the maximum 
number of trials allowed.*/

#include <stdio.h>
#include <stdlib.h>

#define MAX_NO_TRIALS 10

void srand(){
	
}

int main(){
	 printf("%d", rand());
	return 0;
}