/*HW1 Problem b
JohnAnthony Dobson
CS 3335
Fall 2018
8/25/18*/

/* Write a C-program to guess a random integer, between 0 and 100, 
that has been generated by the program. The program should restrict 
user for fixed number of trials (maximum 10). Each incorrect guess 
should be identified as “Too high” or “Too low”. If guessed correctly 
within the trial limit, appropriate success message should be displayed 
before terminating the program. If number of attempts is exhausted, 
the user should be notified and the generated number should be displayed 
before terminating the program. Use global constant to set the maximum 
number of trials allowed.*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h> /*added to get rid of warning of implicit declaration*/

#define MAX_NO_TRIALS 10
	


int main(){
	int ans, trial;
	srand(time(NULL));
	int randNum = 0 + rand()%101;
	/*printf("%d\n", randNum); uncomment to reveal answer from the start*/
	
	printf("Try and guess the mystery number: ");
	trial = 0;
	while (ans != randNum && trial < MAX_NO_TRIALS) {
		scanf("%d", &ans);
		if(ans == randNum) {
			printf("\nCorrect! You guessed %d and the number was %d, Good job!\n", ans, randNum);
		} else if(ans > randNum && trial != (MAX_NO_TRIALS-1)) {
			trial++;
 			printf("\nNope! %d is higher than the mystery number. Try again!", ans);
 			printf("\nYou have %d guess(es) left: ", 10-trial);
		} else if(ans < randNum && trial != (MAX_NO_TRIALS-1)) {
			trial++;
 			printf("\nNope! %d is lower than the mystery number. Try again!", ans);
 			printf("\nYou have %d guess(es) left: ", 10-trial);
		} else {
			trial++;
			printf("\nLast guess of %d was incorrect, the answer is %d. Game over!\n", ans, randNum);
		}
	}


	return 0;
}